import { Geist, Geist_Mono, Oswald, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const oswald = Oswald({
	variable: "--font-oswald",
	subsets: ["latin"],
});

const roboto = Roboto({
	variable: "--font-roboto",
  subsets: ['latin']
});
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${oswald.variable} ${roboto.variable} grid max-w-5xl grid-cols-5 mx-auto bg-background antialiased`}>
				{children}
				<Navbar />
			</body>
		</html>
	);
}
